// This file was auto-generated by Fern from our API Definition.

import type * as Robomail from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListMessagesRequest {
    inbox_email_address?: string;
    thread_id?: string;
    direction?: Robomail.ListMessagesRequestDirection;
    from?: string;
    to?: string;
    limit?: number;
    /** Cursor for pagination (message ID of the last item). */
    starting_after?: string;
}
