"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.InboxList = void 0;
var InboxList;
(function (InboxList) {
    InboxList.Object_ = {
        List: "list",
    };
})(InboxList || (exports.InboxList = InboxList = {}));
//# sourceMappingURL=InboxList.js.map