// This file was auto-generated by Fern from our API Definition.

import type * as Robomail from "../index.js";

export interface InboxList {
    object: InboxList.Object_;
    data: Robomail.Inbox[];
    has_more: boolean;
    next_cursor?: (string | null) | undefined;
}

export namespace InboxList {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
