// This file was auto-generated by Fern from our API Definition.

export interface Inbox {
    /** Inbox ID (same as address) */
    id: string;
    address: string;
    display_name?: (string | null) | undefined;
    metadata: Record<string, unknown>;
    created_at: string;
}
