// This file was auto-generated by Fern from our API Definition.

import type * as AgentmailDemoApi from "../index.js";

export interface MessageList {
    object: MessageList.Object_;
    data: AgentmailDemoApi.Message[];
    has_more: boolean;
    next_cursor?: (string | null) | undefined;
}

export namespace MessageList {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
