// This file was auto-generated by Fern from our API Definition.

export interface Message {
    /** RFC 5322 Message-ID (normalized, without angle brackets) */
    id: string;
    thread_id: string;
    inbox_email_address: string;
    direction: Message.Direction;
    message_id_header: string;
    in_reply_to?: (string | null) | undefined;
    from: string;
    to: string[];
    cc: string[];
    bcc: string[];
    subject?: (string | null) | undefined;
    body_text?: (string | null) | undefined;
    body_html?: (string | null) | undefined;
    headers: Record<string, unknown>;
    status: Message.Status;
    created_at: string;
}

export namespace Message {
    export const Direction = {
        Inbound: "inbound",
        Outbound: "outbound",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
    export const Status = {
        Sent: "sent",
        Received: "received",
        Delivered: "delivered",
        Bounced: "bounced",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
