"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.Message = void 0;
var Message;
(function (Message) {
    Message.Direction = {
        Inbound: "inbound",
        Outbound: "outbound",
    };
    Message.Status = {
        Sent: "sent",
        Received: "received",
        Delivered: "delivered",
        Bounced: "bounced",
    };
})(Message || (exports.Message = Message = {}));
//# sourceMappingURL=Message.js.map