"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageList = void 0;
var MessageList;
(function (MessageList) {
    MessageList.Object_ = {
        List: "list",
    };
})(MessageList || (exports.MessageList = MessageList = {}));
//# sourceMappingURL=MessageList.js.map