// This file was auto-generated by Fern from our API Definition.

import type * as Robomail from "../index.js";

export interface ThreadWithSimilarity extends Robomail.Thread {
    similarity: number;
}
