// This file was auto-generated by Fern from our API Definition.

import type * as AgentmailDemoApi from "../index.js";

export interface Thread {
    id: string;
    inbox_email_address: string;
    subject?: (string | null) | undefined;
    root_message_id_header: string;
    last_message_at?: (string | null) | undefined;
    created_at: string;
    messages: AgentmailDemoApi.Message[];
}
