// This file was auto-generated by Fern from our API Definition.

import type * as Robomail from "../index.js";

export interface ThreadSearchList {
    object: ThreadSearchList.Object_;
    data: Robomail.ThreadWithSimilarity[];
    has_more: boolean;
    next_cursor?: (string | null) | undefined;
}

export namespace ThreadSearchList {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
