"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThreadSearchList = void 0;
var ThreadSearchList;
(function (ThreadSearchList) {
    ThreadSearchList.Object_ = {
        List: "list",
    };
})(ThreadSearchList || (exports.ThreadSearchList = ThreadSearchList = {}));
//# sourceMappingURL=ThreadSearchList.js.map