"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThreadList = void 0;
var ThreadList;
(function (ThreadList) {
    ThreadList.Object_ = {
        List: "list",
    };
})(ThreadList || (exports.ThreadList = ThreadList = {}));
//# sourceMappingURL=ThreadList.js.map