// This file was auto-generated by Fern from our API Definition.

import type * as AgentmailDemoApi from "../index.js";

export interface ThreadWithSimilarity extends AgentmailDemoApi.Thread {
    similarity: number;
}
