// This file was auto-generated by Fern from our API Definition.

import type * as AgentmailDemoApi from "../index.js";

export interface WebhookEndpointList {
    object: WebhookEndpointList.Object_;
    data: AgentmailDemoApi.WebhookEndpoint[];
}

export namespace WebhookEndpointList {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
