// This file was auto-generated by Fern from our API Definition.

import type * as AgentmailDemoApi from "../index.js";

export interface WebhookEndpointWithSecret extends AgentmailDemoApi.WebhookEndpoint {
    /** Shown only on creation and after rotation. */
    signing_secret: string;
}
