"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookEndpointList = void 0;
var WebhookEndpointList;
(function (WebhookEndpointList) {
    WebhookEndpointList.Object_ = {
        List: "list",
    };
})(WebhookEndpointList || (exports.WebhookEndpointList = WebhookEndpointList = {}));
//# sourceMappingURL=WebhookEndpointList.js.map