"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentmailDemoApiTimeoutError = void 0;
class AgentmailDemoApiTimeoutError extends Error {
    constructor(message, opts) {
        super(message);
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }
        this.name = this.constructor.name;
        if (opts?.cause != null) {
            this.cause = opts.cause;
        }
    }
}
exports.AgentmailDemoApiTimeoutError = AgentmailDemoApiTimeoutError;
//# sourceMappingURL=AgentmailDemoApiTimeoutError.js.map