"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentmailDemoApiClient = void 0;
const Client_js_1 = require("./api/resources/inboxes/client/Client.js");
const Client_js_2 = require("./api/resources/internalWebhooks/client/Client.js");
const Client_js_3 = require("./api/resources/messages/client/Client.js");
const Client_js_4 = require("./api/resources/meta/client/Client.js");
const Client_js_5 = require("./api/resources/threads/client/Client.js");
const Client_js_6 = require("./api/resources/webhookEndpoints/client/Client.js");
const BaseClient_js_1 = require("./BaseClient.js");
const core = __importStar(require("./core/index.js"));
class AgentmailDemoApiClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_js_1.normalizeClientOptionsWithAuth)(options);
    }
    get meta() {
        return (this._meta ?? (this._meta = new Client_js_4.MetaClient(this._options)));
    }
    get inboxes() {
        return (this._inboxes ?? (this._inboxes = new Client_js_1.InboxesClient(this._options)));
    }
    get threads() {
        return (this._threads ?? (this._threads = new Client_js_5.ThreadsClient(this._options)));
    }
    get messages() {
        return (this._messages ?? (this._messages = new Client_js_3.MessagesClient(this._options)));
    }
    get webhookEndpoints() {
        return (this._webhookEndpoints ?? (this._webhookEndpoints = new Client_js_6.WebhookEndpointsClient(this._options)));
    }
    get internalWebhooks() {
        return (this._internalWebhooks ?? (this._internalWebhooks = new Client_js_2.InternalWebhooksClient(this._options)));
    }
    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    async fetch(input, init, requestOptions) {
        return core.makePassthroughRequest(input, init, {
            baseUrl: this._options.baseUrl ?? this._options.environment,
            headers: this._options.headers,
            timeoutInSeconds: this._options.timeoutInSeconds,
            maxRetries: this._options.maxRetries,
            fetch: this._options.fetch,
            logging: this._options.logging,
            getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
        }, requestOptions);
    }
}
exports.AgentmailDemoApiClient = AgentmailDemoApiClient;
//# sourceMappingURL=Client.js.map