// This file was auto-generated by Fern from our API Definition.

export const RobomailEnvironment = {
    Production: "https://agentmail-demo.vercel.app",
} as const;

export type RobomailEnvironment = typeof RobomailEnvironment.Production;
