"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentmailDemoApiEnvironment = void 0;
exports.AgentmailDemoApiEnvironment = {
    Production: "https://agentmail-demo.vercel.app",
};
//# sourceMappingURL=environments.js.map