// This file was auto-generated by Fern from our API Definition.

export const AgentmailDemoApiEnvironment = {
    Production: "https://agentmail-demo.vercel.app",
} as const;

export type AgentmailDemoApiEnvironment = typeof AgentmailDemoApiEnvironment.Production;
