// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteInboxRequest {
    /** Inbox ID (email address). */
    id: string;
}
