// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateInboxRequest {
    /** Inbox ID (email address). */
    id: string;
    display_name?: string | null;
    metadata?: Record<string, unknown>;
}
