// This file was auto-generated by Fern from our API Definition.

export const ListMessagesRequestDirection = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
export type ListMessagesRequestDirection =
    (typeof ListMessagesRequestDirection)[keyof typeof ListMessagesRequestDirection];
