"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListMessagesRequestDirection = void 0;
exports.ListMessagesRequestDirection = {
    Inbound: "inbound",
    Outbound: "outbound",
};
//# sourceMappingURL=ListMessagesRequestDirection.js.map