// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateWebhookEndpointRequest {
    id: string;
    url?: string;
    description?: string | null;
    subscribed_events?: string[];
    is_enabled?: boolean;
}
