// This file was auto-generated by Fern from our API Definition.

export interface GetHealthResponse {
    status: GetHealthResponse.Status;
    version: string;
    uptime_seconds: number;
}

export namespace GetHealthResponse {
    export const Status = {
        Ok: "ok",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
