"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetHealthResponse = void 0;
var GetHealthResponse;
(function (GetHealthResponse) {
    GetHealthResponse.Status = {
        Ok: "ok",
    };
})(GetHealthResponse || (exports.GetHealthResponse = GetHealthResponse = {}));
//# sourceMappingURL=GetHealthResponse.js.map