// This file was auto-generated by Fern from our API Definition.

export interface GetMeResponse {
    account: GetMeResponse.Account;
    api_key: GetMeResponse.ApiKey;
}

export namespace GetMeResponse {
    export interface Account {
        id: string;
        name: string;
        created_at: string;
    }

    export interface ApiKey {
        id: string;
        name: string;
        prefix: string;
    }
}
