// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface SearchThreadsRequest {
    /** Natural-language search query. */
    query: string;
    /** Optional — restrict search to a single inbox. */
    inbox_email_address?: string;
    limit?: number;
}
